services:
  api:
    build:
      context: ..
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname  # Updated to point to the single database service
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

  # Single database service replacing all duplicate DB microservices
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"


