services:
  api:
    build:
      context: ..
      dockerfile: api.dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_net
    environment:
      - DATABASE_URL=postgresql://postgres_user:postgres_password@db:5432/app_db
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: frontend.dockerfile
    ports:
      - "8501:8501"
    networks:
      - app_net
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

  # Single database service replacing all duplicate DB microservices
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge


