
services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    networks:
      app_net:
        aliases:
          - api   # Ensures the hostname 'api' resolves inside Docker
    environment:
      - DATABASE_URL=postgresql://postgres:your_password@db:5432/your_db  # Adjusted to match DB settings
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app_net
    environment:
      - API_URL=http://api:8000  # Uses the Docker alias
    depends_on:
      - api
    restart: unless-stopped

  # Single database service using a custom Dockerfile
  db:
    build:
      context: ..
      dockerfile: docker/db.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
volumes: # Add this top-level key
  postgres_data: {}



